# Generated by Django 4.0.5 on 2022-06-29 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Probe', '0002_alter_probelist_note_alter_probemodeldetail_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probelist',
            name='ModelID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Probe.probemodeldetail'),
        ),
        migrations.AlterField(
            model_name='probelist',
            name='Note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='probemodeldetail',
            name='Note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
