# Generated by Django 4.0.5 on 2022-06-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Probe', '0003_alter_probelist_modelid_alter_probelist_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='probemodeldetail',
            name='UsedCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
