# Generated by Django 4.0.5 on 2022-06-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Probe', '0004_probemodeldetail_usedcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probemodeldetail',
            name='UsedCount',
            field=models.IntegerField(),
        ),
    ]
